spring:
  application:
    name: api
    
server:
  port: 80
  
zuul:
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 20000
  prefix: /test
  routes:
    users: 
      path: /user/**
      serviceId: user
      stripPrefix: true
    hello: 
      path: /hello/**
      serviceId: hello
      stripPrefix: true
      
eureka:
  client:
    serviceUrl: 
      defaultZone: http://peer1:1111/eureka/
      
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 10
  
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000