from: git-test-2.0
spring:
  application:
    name: user
  rabiitmq:
    host: wusc.com
    port: 15672
    username: wusc
    password: 123456
server:
  port: 8082
eureka:
  client:
    serviceUrl: 
      defaultZone: http://peer1:1111/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 1000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
