spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wusichao/spring-cloud.git
          searchPaths: /cloud-config
          username: wusichao
          password: wsc15171545112
server:
  port: 6001
eureka: 
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/
  instance:
    preferIpAddress: false
    hostName: config-server